---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: jenkins-home-storage-class
  local:
    path: /media/usb-drive/jenkins_home
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - jenkins_home
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home-claim
spec:
  storageClassName: jenkins-home-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # if you try to claim more storage than is available, it will
      # hang on pending.
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-pvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
        env: test
    spec:
      nodeSelector:
        storage: jenkins_home
      containers:
        - name: jenkins
          image: paulwroe/jenkins:v11
          env:
            - name: JAVA_OPTS
            # false sets up jenkins without security on first run!
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-storage-claim
              mountPath: /var/jenkins_home
            # bind node docker to container
            - name: docker-bin
              mountPath: /usr/bin/docker
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-storage-claim
          persistentVolumeClaim:
            claimName: jenkins-home-claim
        # bind node docker to container
        - name: docker-bin
          hostPath:
            path: /usr/bin/docker
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
